// <auto-generated />
using System;
using DatabasePractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabasePractice.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220216165603_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DatabasePractice.Models.Icecream", b =>
                {
                    b.Property<int>("IcecreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Container")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Flavor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Topping")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("hasCherry")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IcecreamId");

                    b.ToTable("Icecream");
                });
#pragma warning restore 612, 618
        }
    }
}
